### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by k-dominik** [janelia-cellmap/pydantic-zarr#27]
Hello @d-v-b,

quick question regarding python compatibility of this package. It seems python 3.10 and up are tested:
https://github.com/janelia-cellmap/pydantic-zarr/blob/fbe124cdd6135eaf335645ec187f2fb22da2abab/.github/workflows/test.yml#L14

but 3.9 should also be supported:
https://github.com/janelia-cellmap/pydantic-zarr/blob/fbe124cdd6135eaf335645ec187f2fb22da2abab/pyproject.toml#L10

.
I checked in an environment using python 3.9 and `import pydantic_zarr.v2` fails with Traceback (paths shortened):

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../python3.9/site-packages/pydantic_zarr/v2.py", line 25, in <module>
    from pydantic_zarr.core import (
  File ".../python3.9/site-packages/pydantic_zarr/core.py", line 2, in <module>
    from typing import (
ImportError: cannot import name 'TypeAlias' from 'typing' (.../python3.9/typing.py)

```

Which can be fixed by importing from `typing_extensions`.

Since this package is also a requirement for `pydantic-ome-zarr`, do you consider keeping/adding support for Python 3.9 here?

**Comment by d-v-b** [comment]
> Since this package is also a requirement for pydantic-ome-zarr, do you consider keeping/adding support for Python 3.9 here?

Yeah, I think this is reasonable. There are a few other changes I want to make today, so I can get a release out shortly

**Comment by k-dominik** [comment]
wow, thanks for the super fast response!

**Comment by d-v-b** [comment]
this should be sorted out by https://github.com/janelia-cellmap/pydantic-zarr/pull/28 (which contains some other stuff, too)

**Comment by d-v-b** [comment]
closed as completed
